# -*- coding: utf-8 -*-
"""Pytbhon_image_remover.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19yRO028cVeDiD0SWQ8sC6ZMMjj3WtKAu
"""

!pip install rembg
!pip install onnxruntime

from rembg import remove
from PIL import Image
from google.colab import files

uploaded = files.upload()

for filename in uploaded.keys():
    input_image = Image.open(filename)

output_image = remove(input_image)
output_image.save("Image_without_bg.png")